### ISSUE TITLE
Got com.xendit.exception.XenditException: Connection error Exception

### ISSUE THREAD

**Issue by huzairuje** [xendit/xendit-java#106]
got com.xendit.exception.XenditException: Connection error Exception when using this method
`FixedVirtualAccountPayment fixedVirtualAccountPayment = FixedVirtualAccount.getPayment(id);` 
and also this method
`HashMap<String, Object> params = new HashMap<>();
 params.put("expiration_date", date);
 FixedVirtualAccount.update(paymentId, params);`
 
 and instead i got this error 
 
![image](https://user-images.githubusercontent.com/4037159/147254119-30d074af-cb79-4bb0-a965-4b2a8077c7b7.png)

i am using this version on gradle 
`implementation 'com.xendit:xendit-java-lib:1.18.0'`
OS that i am using 
`Pop!_OS` that is derivative from ubuntu

and using java version 
`openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)`

and using gradle version 
`7.0.2`
![image](https://user-images.githubusercontent.com/4037159/147254806-a38da913-59bf-4de1-a49f-ad80a5f4d60d.png)

**Comment by bob-xendit** [comment]
Hi @huzairuje , we are currently checking this, please give us sometime and we will revert to you back ASAP.

**Comment by huzairuje** [comment]
hello @bob-xendit , thanks looking forward to this. hope this fix asap.

**Comment by bob-xendit** [comment]
Hi @huzairuje ,

Can you double check on the library you used? Is it v1.18.0, we have a fix for the connection in v1.17.0.
this is the PR. https://github.com/xendit/xendit-java/pull/100/files

And also I tried to create a sample code and able to get the expected result.
![image](https://user-images.githubusercontent.com/92286875/147330611-2f66168f-9f0c-4642-ab56-ab9d4827ed8e.png)

**Comment by huzairuje** [comment]
okay @bob-xendit i will post the result soon.

**Comment by xen-HendryZheng** [comment]
Hi @huzairuje would like to check on your integration progress? Is everything ok with the process? Do you still hit the connection?

**Comment by huzairuje** [comment]
hi @xen-HendryZheng , it has been resolved, i need to reinvalidate the local cache for the SDK client itself. thanks guys @luminto17  @bob-xendit
