### ISSUE TITLE
For-user-id header not working in Update Virtual Account API

### ISSUE THREAD

**Issue by roby-buku** [xendit/xendit-java#107]
https://developers.xendit.co/api-reference/?java#update-virtual-account
Hi, 
1) i would like to report the api documentation is not correct since when i try to made a request without using `for-user-id` it will return 400 
```
{
    "error_code": "INVALID_CALLBACK_VIRTUAL_ACCOUNT_ERROR",
    "message": "Could not update this virtual account because it is not accessible by you"
} 
```

2) Since the request need a header then this code won't work
https://github.com/xendit/xendit-java/blob/149c2ac6ce0d5f41aba0049137d69c67521cd583/xendit-java-lib/src/main/java/com/xendit/model/FixedVirtualAccountClient.java#L113

3) When i tried to update `expiration_date` on the dev env it did not get updated, what is the correct way to made the virtual account expired ?

**Comment by luminto17** [comment]
Hi @roby-buku , thanks for the report!

For issue #1, do you mind to provide us the sample payload, so we can check it?

Final question, which Java version are you using?
Note that there was a known issue that Java lib can't invoke PATCH API, but we have fixed it in v1.17.0 back in October https://github.com/xendit/xendit-java/releases/tag/v1.17.0

**Comment by roby-buku** [comment]
Hi @luminto17 
This is the sample 
`curl --location --request PATCH 'https://api.xendit.co/callback_virtual_accounts/61c9ae81522968d4236a1f5f' \
--header 'Authorization: Basic eG5kX2RldmVsb3BtZW50X0llVHdLdHROVkxNVjlYUVJKZGhVQmdTTW0zcXdrWkhISzdGME1CbFlNSFFiWkxaczVNVXFBMFl5SkJRR2lzOg==' \
--header 'Accept-Encoding: application/json' \
--header 'for-user-id: 61a721b73e71a66df60a9006' \
--header 'Content-Type: text/plain' \
--header 'Cookie: incap_ses_1122_2182539=LWaVMIe5YnFkRiQOfiWSDydvymEAAAAAnKTkS6GhJc+QjC1CQDh2tw==; nlbi_2182539=NQaQPuGuCVJywmJajjCKbQAAAAC0ur8FEC1lykbfiw4z4a6c' \
--data-raw '{
    "expiration_date" : "2021-12-27T14:00:58.765Z"
}'`

I am using java 8, i think the spec are different so it did not matter which xendit-java-lib version i used it will be an error if i did not send the`for-user-id` as i stated on issue 1

**Comment by luminto17** [comment]
got it - can you immediately remove the `Authorization` header from sample payload above for security purpose?

we'll take a look at it and give update when we have one

**Comment by luminto17** [comment]
got it @roby-buku - can you immediately remove the `Authorization` header from sample payload above for security purpose?

we'll take a look at it and give update when we have one

**Comment by luminto17** [comment]
hi @roby-buku , thank you for waiting for our response

We found out that issue can be reproduced and we have released the fix in newer version https://github.com/xendit/xendit-java/releases/tag/v1.19.0

Let us know if you need more assistance

**Comment by roby-buku** [comment]
Okay thank you for the help @luminto17 , will close the ticket after testing it
