### ISSUE TITLE
Missing feature unable to access request ID

### ISSUE THREAD

**Issue by xen-HendryZheng** [xendit/xendit-java#130]
Context (What are Merchant Inquiries/Questions?) *
- the merchant asked where can they find the request id of each request in our Java SDK
- reason of asking is, they would like to use the request id to search for each request in dashboard > API logs tab
- they are aware they need to get request id in the response headers, but unsure how to get this in Java, as our [example](https://docs.xendit.co/api-integration/api-logs) is in postman collection

**Comment by adityarx** [comment]
Closing as this is resolved in #133
