### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by kevindavee** [xendit/xendit-java#27]
Need to setup Travis CI as the Open Source CI

**Comment by stanleynguyen** [comment]
Shall we `Github Actions` instead? 🥳

**Comment by stanleynguyen** [comment]
Main point of this is automated unit tests and integration test checks on every PR

**Comment by kevindavee** [comment]
Yes, I agree. Github Actions is better because we can monitor the CI in the same platform as the SDK itself

**Comment by kevindavee** [comment]
@stanleynguyen can you help on this one? Since you are more familiar with Github actions
