### ISSUE TITLE
Could not find com.xendit:xendit-java-lib:1.0.0

### ISSUE THREAD

**Issue by shengxiaozi** [xendit/xendit-java#42]
My java project want to intergate xendit pay,and use gradle  add compile 'com.xendit:xendit-java-lib:1.0.0'  
but :

Could not find com.xendit:xendit-java-lib:1.0.0.
Searched in the following locations:
  - http://maven.aliyun.com/nexus/content/groups/public/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.pom
  - http://maven.aliyun.com/nexus/content/groups/public/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.jar
  - http://dist.wso2.org/maven2/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.pom
  - http://dist.wso2.org/maven2/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.jar
  - https://jcenter.bintray.com/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.pom
  - https://jcenter.bintray.com/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.jar
  - file:/C:/Users/USER/.m2/repository/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.pom
  - file:/C:/Users/USER/.m2/repository/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.jar
  - https://repo.maven.apache.org/maven2/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.pom
  - https://repo.maven.apache.org/maven2/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.jar
  - https://oss.sonatype.org/content/repositories/snapshots/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.pom
  - https://oss.sonatype.org/content/repositories/snapshots/com/xendit/xendit-java-lib/1.0.0/xendit-java-lib-1.0.0.jar

**Comment by stanleynguyen** [comment]
Have u added bintray config like what we've listed here https://github.com/xendit/xendit-java#installation
On another note, we would recommend the latest version `1.6.0`

**Comment by shengxiaozi** [comment]
ok,thinks

**Comment by stanleynguyen** [comment]
Did that solve your problem @shengxiaozi ?

**Comment by stanleynguyen** [comment]
Stale
