### ISSUE TITLE
FixedVirtualAccount.create()

### ISSUE THREAD

**Issue by alviansyahexza** [xendit/xendit-java#56]
get exception : com.xendit.exception.ApiException: There was an error with the format submitted to the server.
with this calling : FixedVirtualAccount.createClosed("LZZGWG", BankCode.BCA.text, "PT. TARGET SUKSES SINERGI", 1200000)

**Comment by stanleynguyen** [comment]
Hi @alviansyahexza, your name param is invalid. It must satisfy this regex `/^[a-zA-Z0-9\\s?]+$/`
Please consider removing `.`
