### ISSUE TITLE
NoSuchFieldException on Java 12

### ISSUE THREAD

**Issue by f3l1xss** [xendit/xendit-java#58]
Hi As of Java 12 accessing Field.class fields through reflection is forbidden,

https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12

thus it will break this following function inside baseRequest:

private static void allowHttpMethods(String... methods) {
        try {
            Field methodsField = HttpURLConnection.class.getDeclaredField("methods");
            Field modifiersField = Field.class.getDeclaredField("modifiers");
            modifiersField.setAccessible(true);
            modifiersField.setInt(methodsField, methodsField.getModifiers() & -17);
            methodsField.setAccessible(true);
            String[] oldMethods = (String[])methodsField.get((Object)null);
            Set<String> methodsSet = new LinkedHashSet(Arrays.asList(oldMethods));
            methodsSet.addAll(Arrays.asList(methods));
            String[] newMethods = (String[])methodsSet.toArray(new String[0]);
            methodsField.set((Object)null, newMethods);
        } catch (IllegalAccessException | NoSuchFieldException var6) {
            throw new IllegalStateException(var6);
        }
    }

Not sure why that function needed to be there at the first place

**Comment by stanleynguyen** [comment]
Hey @f3l1xss, thanks for reporting. I want to clean up this redundant function as well. Would you like to open a PR to remove it?

**Comment by f3l1xss** [comment]
Okay done
