### ISSUE TITLE
Invalid HTTP Method PATCH

### ISSUE THREAD

**Issue by stanleynguyen** [xendit/xendit-java#95]
This is a quirk from the java stdlib
https://newbedev.com/httpurlconnection-invalid-http-method-patch

The current finding is that the removed method from #58 is actually a work-around for this issue.
Next step:
- Create integration tests with actual Xendit API to reproduce this error and catch similar errors earlier in GH Actions
- Consider adding back the work around while not re-introducing the same problem in #58, or we could consider using a different http client

**Comment by luminto17** [comment]
this is solved in v1.17.0 https://github.com/xendit/xendit-java/releases/tag/v1.17.0
